common:
  http:
    enabled: true
    port: 8881
  ws:
    enabled: false
    port: 8081

storage:
  token: "12345"
  url: "http://localhost:8880"
  collection: "Cyclone"

notifier:
  sender_id: "Cyclone"
  token: "12345"
  url: "http://localhost:8885"

cyclone:
  node_address: "http://164.68.127.226:9231"
  start_block: 2609
  sleep_duration: 2
